services: 
  server:
    image: 'nginx:stable-alpine'
    ports: 
      - '8000:80'
    volumes: 
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  php:
    build: 
      context: ./dockerfiles
      dockerfile: php.dockerfile
    volumes:
      # delegated es una optimizacion para la actualizacion se haga en backgound y mejora los tiempos
      - ./src:/var/www/html:delegated
    # Esta configuracion no se necesita ya que la comunicacion es interna entre containers
    # ports: 
    #   - '3000:9000'  #(host:internal docker container port)
  mysql:
    image: mysql:5.7
    env_file:
      - ./env/mysql.env
  composer:
    build: 
      context: ./dockerfiles
      dockerfile: composer.dockerfile
    volumes:
      - ./src:/var/www/html
  # artisan:
  # npm: